TRUNCATE TABLE nc_land_allowed_usage;
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'141','141000000000','Земли сельскохозяйственного назначения');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'141.1','141001000000','Для сельскохозяйственного производства');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'141.1.1','141001001000','Для использования в качестве сельскохо-зяйственных угодий');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'141.1.2','141001002000','Для размещения зданий, строений, соору-жений, используемых для производства, хранения и первичной переработки сельскохозяйственной продукции');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'141.1.3','141001003000','Для размещения внутрихозяйственных дорог и коммуникаций');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'141.1.4','141001004000','Для размещения водных объектов');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'141.1.5','141001005000','Для размещения иных объектов, связанных с сельскохозяйственным производством');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'141.2','141002000000','Для ведения крестьянского (фермерского) хозяйства');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'141.3','141003000000','Для ведения личного подсобного хозяйства');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'141.4','141004000000','Для индивидуального садоводства и огородничества');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'141.5','141005000000','Для индивидуального животноводства');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'141.6','141006000000','Для ведения дачного хозяйства');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'141.7','141007000000','Для создания защитных насаждений');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'141.8','141008000000','Для научно-исследовательских целей');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'141.9','141009000000','Для учебных целей');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'141.10','141010000000','Для сенокошения и выпаса скота');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'141.11','141011000000','Фонд перераспределения');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'141.12','141012000000','Для иных видов разрешенного сельскохозяйственного использования');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'142','142000000000','Земли поселений');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'142.1','142001000000','Виды сельскохозяйственного использования');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'142.1.1','142001001000','Для сельскохозяйственного производства');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'142.1.1.1','142001001001','Для использования в качестве сельскохозяйственных угодий');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'142.1.1.2','142001001002','Для размещения зданий, строений, сооружений, используемых для производства, хранения и первичной переработки сельскохозяйственной продукции');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'142.1.1.3','142001001003','Для размещения внутрихозяйственных дорог и коммуникаций');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'142.1.1.4','142001001004','Для размещения водных объектов сельскохозяйственного назначения');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'142.1.1.5','142001001005','Для размещения иных объектов, связанных с сельскохозяйственным производством на землях поселений');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'142.1.2','142001002000','Для ведения крестьянского (фермерского) хозяйства');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'142.1.3','142001003000','Для ведения личного подсобного хозяйства');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'142.1.4','142001004000','Для индивидуального садоводства и огородничества');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'142.1.5','142001005000','Для индивидуального животноводства');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'142.1.6','142001006000','Для ведения дачного хозяйства');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'142.1.7','142001007000','Для создания защитных насаждений');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'142.1.8','142001008000','Для научно-исследовательских целей');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'142.1.9','142001009000','Для учебных целей');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'142.1.10','142001010000','Для сенокошения и выпаса скота');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'142.1.11','142001011000','Для иных видов разрешенного сельскохозяйственного использования в черте земель поселений');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'142.2','142002000000','Виды использования, характерные для населенных пунктов');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'142.2.1','142002001000','Для объектов жилой застройки');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'142.2.1.1','142002001001','Для индивидуального жилого дома');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'142.2.1.2','142002001002','Для многоквартирной застройки');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'142.2.1.2.1','142002001021','Для малоэтажной застройки');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'142.2.1.2.2','142002001022','Для среднеэтажной застройки');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'142.2.1.2.3','142002001023','Для многоэтажной застройки');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'142.2.1.2.4','142002001024','Для иных видов жилой застройки');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'142.2.1.3','142002001003','Для размещения объектов дошкольного, начального, общего и среднего (полного) общего образования');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'142.2.1.4','142002001004','Для размещения иных объектов, допустимых в жилых зонах и не перечисленных в классификаторе');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'142.2.2','142002002000','Для объектов общественно-делового значения');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'142.2.2.1','142002002001','Для размещения объектов социального и коммунально-бытового назначения');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'142.2.2.2','142002002002','Для размещения объектов здравоохранения');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'142.2.2.3','142002002003','Для размещения объектов культуры');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'142.2.2.4','142002002004','Для размещения объектов торговли');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'142.2.2.5','142002002005','Для размещения объектов общественного питания');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'142.2.2.6','142002002006','Для размещения объектов предпринимательской деятельности');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'142.2.2.7','142002002007','Для размещения объектов среднего профессионального и высшего профессионального образования');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'142.2.2.8','142002002008','Для размещения административных зданий');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'142.2.2.9','142002002009','Для размещения научно-исследовательских учреждений');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'142.2.2.10','142002002010','Для размещения культовых зданий');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'142.2.2.11','142002002011','Для стоянок автомобильного транспорта');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'142.2.2.12','142002002012','Для размещения объектов делового назначения');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'142.2.2.13','142002002013','Для размещения объектов финансового назначения');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'142.2.2.14','142002002014','Для размещения гостиниц');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'142.2.2.15','142002002015','Для размещения подземных или много-этажных гаражей');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'142.2.2.16','142002002016','Для размещения индивидуальных гаражей');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'142.2.2.17','142002002017','Для размещения иных объектов общественно-делового значения, обеспечивающих жизнь граждан');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'142.2.3','142002003000','Для общего пользования (уличная сеть)');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'142.2.4','142002004000','Для размещения объектов специального назначения');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'142.2.4.1','142002004001','Для размещения кладбищ');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'142.2.4.2','142002004002','Для размещения крематориев');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'142.2.4.3','142002004003','Для размещения скотомогильников');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'142.2.4.4','142002004004','Под объектами размещения отходов потребления');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'142.2.4.5','142002004005','Под иными объектами специального назначения');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'142.2.5','142002005000','Для размещения коммунальных, складских объектов');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'142.2.6','142002006000','Для размещения объектов жилищно-коммунального хозяйства');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'142.2.7','142002007000','Неиспользуемые земли в черте населенных пунктов');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'142.2.8','142002008000','Для размещения иных объектов, характерных для населенных пунктов');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'142.3','142003000000','Для объектов производственной, инженерной и транспортной инфраструктур');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'142.3.1','142003001000','Для размещения объектов промышленности');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'142.3.2','142003002000','Для размещения объектов энергетики');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'142.3.3','142003003000','Для размещения объектов транспорта');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'142.3.3.1','142003003001','Для размещения и эксплуатации объектов железнодорожного транспорта');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'142.3.3.2','142003003002','Для размещения и эксплуатации объектов автомобильного транспорта и объектов дорожного хозяйства');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'142.3.3.3','142003003003','Для размещения и эксплуатации объектов морского, внутреннего водного транспорта');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'142.3.3.4','142003003004','Для размещения и эксплуатации объектов воздушного транспорта');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'142.3.3.5','142003003005','Для размещения и эксплуатации объектов трубопроводного транспорта');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'142.3.3.6','142003003006','Для размещения иных объектов транспорта');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'142.3.4','142003004000','Для размещения объектов связи, радиовещания, телевидения, информатики');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'142.3.5','142003005000','Для обеспечения космической деятельности');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'142.3.6','142003006000','Для размещения объектов обороны и безопасности');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'142.3.7','142003007000','Для размещения иных объектов производственной, инженерной и транспортной инфраструктур');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'142.4','142004000000','Земли особо охраняемых территорий и объектов в пределах черты поселений');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'142.4.1','142004001000','Особо охраняемые природные территории');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'142.4.1.1','142004001001','Государственные природные заповедники (в т.ч. биосферные)');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'142.4.1.2','142004001002','Государственные природные заказники');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'142.4.1.3','142004001003','Памятники природы');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'142.4.1.4','142004001004','Национальные парки');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'142.4.1.5','142004001005','Природные парки');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'142.4.1.6','142004001006','Дендрологические парки');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'142.4.1.7','142004001007','Ботанические сады');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'142.4.1.8','142004001008','Лечебно-оздоровительное назначение');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'142.4.1.9','142004001009','Иные особо охраняемые природные территории в пределах черты поселений');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'142.4.2','142004002000','Природоохранное назначение');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'142.4.3','142004003000','Рекреационное назначение');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'142.4.3.1','142004003001','Для размещения домов отдыха, пансионатов, кемпингов');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'142.4.3.2','142004003002','Для размещения объектов физической культуры и спорта');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'142.4.3.3','142004003003','Для размещения туристических баз, стационарных и палаточных туристско-оздоровительных лагерей, домов рыболова и охотника, детских туристических станций');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'142.4.3.4','142004003004','Для размещения туристических парков');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'142.4.3.5','142004003005','Для размещения лесопарков');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'142.4.3.6','142004003006','Для размещения учебно-туристических троп и трасс');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'142.4.3.7','142004003007','Для размещения детских и спортивных лагерей');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'142.4.3.8','142004003008','Для размещения скверов, парков, городских садов');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'142.4.3.9','142004003009','Для размещения пляжей');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'142.4.3.10','142004003010','Для размещения иных объектов рекреационного назначения');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'142.4.4','142004004000','Историко-культурное назначение');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'142.4.5','142004005000','Особо ценные земли');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'142.4.6','142004006000','Иные особо охраняемые территории и объекты в пределах черты поселений');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'142.5','142005000000','Городские леса');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'142.6','142006000000','Для размещения и эксплуатации водных объектов');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'142.6.1','142006001000','Под водными объектами');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'142.6.1.1','142006001001','Под прудами, озерами, реками, каналами');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'142.6.1.2','142006001002','Под водохранилищами');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'142.6.2','142006002000','Для размещения гидротехнических сооружений');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'142.6.3','142006003000','Для размещения водохозяйственных сооружений');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'142.6.4','142006004000','Для размещения и эксплуатации иных водных объектов в пределах черты поселений');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'142.7','142007000000','Для иного назначения, допустимого в черте населенных пунктов');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'143','143000000000','Земли промышленности, энергетики, транспорта, связи, радиовещания, телевидения, информатики, земли для обеспечения космической деятельности, земли обороны, безопасности и земли иного специального назначения');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'143.1','143001000000','Земли промышленности');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'143.1.1','143001001000','Для размещения производственных и административных зданий, строений, сооружений и обслуживания их объектов');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'143.1.1.1','143001001001','Для размещения производственных зданий');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'143.1.1.2','143001001002','Для размещения коммуникаций');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'143.1.1.3','143001001003','Для размещения подъездных путей');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'143.1.1.4','143001001004','Для размещения складских помещений');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'143.1.1.5','143001001005','Для размещения административных зданий');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'143.1.1.6','143001001006','Для размещения культурно-бытовых зданий');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'143.1.1.7','143001001007','Иные производственные и административные здания, строения, сооружения');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'143.1.2','143001002000','Для добычи и разработки полезных ископаемых');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'143.1.3','143001003000','Для размещения иных объектов промышленности');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'143.2','143002000000','Земли энергетики');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'143.2.1','143002001000','Для размещения электростанций и обслуживающих сооружений и объектов');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'143.2.1.1','143002001001','Для размещения гидроэлектростанций');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'143.2.1.2','143002001002','Для размещения атомных станций');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'143.2.1.3','143002001003','Для размещения ядерных установок');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'143.2.1.4','143002001004','Для размещения пунктов ядерных материалов и радиоактивных веществ');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'143.2.1.5','143002001005','Для размещения хранилищ радиоактивных тходов');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'143.2.1.6','143002001006','Для размещения тепловых станций');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'143.2.1.7','143002001007','Для размещения иных типов электростанций');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'143.2.1.8','143002001008','Для размещения иных обслуживающих сооружений и объектов');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'143.2.2','143002002000','Для размещения электрических сетей');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'143.2.2.1','143002002001','Для размещения воздушных линий электропередачи');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'143.2.2.2','143002002002','Для размещения наземных сооружений кабельных линий электропередачи');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'143.2.2.3','143002002003','Для размещения подстанций');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'143.2.2.4','143002002004','Для размещения распределительных пунктов');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'143.2.2.5','143002002005','Для размещения других сооружений и объектов энергетики');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'143.2.3','143002003000','Для размещения иных объектов энергетики');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'143.3','143003000000','Земли транспорта');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'143.3.1','143003001000','Для размещения и эксплуатации объектов железнодорожного транспорта');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'143.3.1.1','143003001001','Для размещения железнодорожных путей (полос отвода)');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'143.3.1.2','143003001002','Для размещения, эксплуатации, расширения и реконструкции строений, зданий, сооружений железнодорожного транспорта');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'143.3.2','143003002000','Для размещения и эксплуатации объектов автомобильного транспорта и объектов дорожного хозяйства');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'143.3.2.1','143003002001','Для размещения автомобильных дорог (полоса отвода)');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'143.3.2.2','143003002002','Для размещения конструктивных элементов и дорожных сооружений');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'143.3.2.3','143003002003','Для размещения автовокзалов и автостанций');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'143.3.2.4','143003002004','Для размещения иных объектов автомобильного транспорта и дорожного хозяйства');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'143.3.3','143003003000','Для размещения и эксплуатации объектов морского, внутреннего водного транспорта');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'143.3.3.1','143003003001','Для размещения искусственно созданных внутренних водных путей');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'143.3.3.2','143003003002','Для размещения морских и речных портов, причалов, пристаней');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'143.3.3.3','143003003003','Для размещения гидротехнических сооружений');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'143.3.3.4','143003003004','Для размещения иных объектов водного транспорта');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'143.3.3.5','143003003005','Для выделения береговой полосы');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'143.3.4','143003004000','Для размещения и эксплуатации объектов воздушного транспорта');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'143.3.4.1','143003004001','Для размещения аэропортов и аэродромов');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'143.3.4.2','143003004002','Для размещения аэровокзалов');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'143.3.4.3','143003004003','Для размещения взлетно-посадочных полос');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'143.3.4.4','143003004004','Для размещения иных наземных объектов воздушного транспорта');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'143.3.5','143003005000','Для размещения и эксплуатации объектов трубопроводного транспорта');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'143.3.5.1','143003005001','Для размещения нефтепроводов');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'143.3.5.2','143003005002','Для размещения газопроводов');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'143.3.5.3','143003005003','Для размещения иных трубопроводов');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'143.3.5.4','143003005004','Для размещения иных объектов трубопроводного транспорта');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'143.3.6','143003006000','Для размещения и эксплуатации иных объектов транспорта');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'143.4','143004000000','Земли связи, радиовещания, телевидения, информатики');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'143.4.1','143004001000','Для размещения эксплуатационных предприятий связи для обслуживания линий связи');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'143.4.2','143004002000','Для размещения кабельных, радиорелейных и воздушных линий связи и линий радиофикации на трассах кабельных и воздушных линий связи и радиофикации и их охранные зоны');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'143.4.3','143004003000','Для размещения подземных кабельных и воздушных линий связи и радиофикации и их охранные зоны');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'143.4.4','143004004000','Для размещения наземных и подземных необслуживаемых усилительных пунктов на кабельных линиях связи и их охранные зоны');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'143.4.5','143004005000','Для размещения наземных сооружений и инфраструктуры спутниковой связи');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'143.4.6','143004006000','Для размещения иных объектов связи, радиовещания, телевидения, информатики');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'143.5','143005000000','Земли для обеспечения космической деятельности');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'143.5.1','143005001000','Для размещения космодромов, стартовых комплексов и пусковых установок');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'143.5.2','143005002000','Для размещения командно-измерительных комплексов, центров и пунктов управления полетами космических объектов, приема, хранения и переработки информации');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'143.5.3','143005003000','Для размещения баз хранения космической техники');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'143.5.4','143005004000','Для размещения полигонов приземления космических объектов и взлетно-посадочных полос');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'143.5.5','143005005000','Для размещения объектов экспериментальной базы для отработки космической техники');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'143.5.6','143005006000','Для размещения центров и оборудования для подготовки космонавтов');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'143.5.7','143005007000','Для размещения других наземных сооружений и техники, используемых при осуществлении космической деятельности');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'143.6','143006000000','Земли обороны и безопасности');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'143.6.1','143006001000','Для обеспечения целей обороны');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'143.6.1.1','143006001001','Для размещения военных организаций, учреждений и других объектов');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'143.6.1.2','143006001002','Для дислокации войск и сил флота');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'143.6.1.3','143006001003','Для проведения учений и иных мероприятий');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'143.6.1.4','143006001004','Для испытательных полигонов');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'143.6.1.5','143006001005','Для мест уничтожения оружия и захоронения отходов');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'143.6.1.6','143006001006','Для создания запасов материальных ценностей в государственном и мобилизационном резервах (хранилища, склады и другие)');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'143.6.1.7','143006001007','Для размещения иных объектов обороны');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'143.6.2','143006002000','Для защиты и охраны Государственной границы РФ');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'143.6.2.1','143006002001','Для обустройства и содержания инженерно-технических сооружений и заграждений');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'143.6.2.2','143006002002','Для обустройства и содержания пограничных знаков');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'143.6.2.3','143006002003','Для обустройства и содержания пограничных просек');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'143.6.2.4','143006002004','Для обустройства и содержания коммуникаций');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'143.6.2.5','143006002005','Для обустройства и содержания пунктов пропуска через Государственную границу РФ');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'143.6.2.6','143006002006','Для размещения иных объектов для защиты и охраны Государственной границы РФ');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'143.6.3','143006003000','Для размещения иных объектов обороны и безопасности');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'143.7','143007000000','Для размещения иных объектов промышленности, энергетики, транспорта, связи, радиовещания, телевидения, информатики, земли для обеспечения космической деятельности, земли обороны, безопасности и земли иного специального назначения');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'144','144000000000','Земли особо охраняемых территорий и объектов');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'144.1','144001000000','Особо охраняемые природные территории');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'144.1.1','144001001000','Государственные природные заповедники (в т.ч. биосферные)');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'144.1.2','144001002000','Государственные природные заказники');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'144.1.3','144001003000','Памятники природы');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'144.1.4','144001004000','Национальные парки');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'144.1.5','144001005000','Природные парки');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'144.1.6','144001006000','Дендрологические парки');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'144.1.7','144001007000','Ботанические сады');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'144.1.8','144001008000','Лечебно-оздоровительное назначение');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'144.1.9','144001009000','Территории традиционного природопользования');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'144.1.10','144001010000','Для размещения иных особо охраняемых природных территорий');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'144.2','144002000000','Природоохранное назначение');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'144.3','144003000000','Рекреационное назначение');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'144.3.1','144003001000','Для размещения домов отдыха, пансионатов, кемпингов');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'144.3.2','144003002000','Для размещения объектов физической культуры и спорта');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'144.3.3','144003003000','Для размещения туристических баз, стационарных и палаточных туристско-оздоровительных лагерей, домов рыболова и охотника, детских туристических станций');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'144.3.4','144003004000','Для размещения туристических парков');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'144.3.5','144003005000','Для размещения лесопарков');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'144.3.6','144003006000','Для размещения учебно-туристических троп и трасс');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'144.3.7','144003007000','Для размещения детских и спортивных лагерей');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'144.3.8','144003008000','Для размещения скверов, парков, городских садов');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'144.3.9','144003009000','Для размещения пляжей');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'144.3.10','144003010000','Для размещения иных объектов рекреационного назначения');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'144.4','144004000000','Историко-культурное назначение');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'144.5','144005000000','Особо ценные земли');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'144.6','144006000000','Для иного разрешенного использования на землях особо охраняемых территорий и объектов');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'145','145000000000','Земли лесного фонда');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'145.1','145001000000','Для ведения лесного хозяйства (лесопользования)');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'145.2','145002000000','Для сельскохозяйственного производства');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'145.3','145003000000','Для иного разрешенного использования, не связанного с лесопользованием');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'146','146000000000','Земли водного фонда');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'146.1','146001000000','Под водными объектами');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'146.2','146002000000','Для размещения гидротехнических сооружений');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'146.3','146003000000','Для размещения водохозяйственных сооружений');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'146.4','146004000000','Для иного разрешенного использования, не связанного с водопользованием');
INSERT INTO nc_land_allowed_usage (id,number,classification_code,name) VALUES (nextval('nc_land_allowed_usage_seq'),'147','147000000000','Земли запаса (неиспользуемые)');
