TRUNCATE TABLE nc_land_category;
INSERT INTO nc_land_category (id, code, name) VALUES (nextval('nc_land_category_seq'),'3001000000','ЗЕМЛИ СЕЛЬСКОХОЗЯЙСТВЕННОГО НАЗНАЧЕНИЯ');
INSERT INTO nc_land_category (id, code, name) VALUES (nextval('nc_land_category_seq'),'3001000010','Сельскохозяйственные угодья');
INSERT INTO nc_land_category (id, code, name) VALUES (nextval('nc_land_category_seq'),'3001000020','Земли, занятые внутрихозяйственными дорогами, коммуникациями, лесными насаждениями, предназначенными для обеспечения защиты земель от воздействия негативных (вредных) природных, антропогенных и техногенных явлений, водными объектами, а также занятые зданиями, строениями, сооружениями, используемыми для производства, хранения и переработки сельскохозяйственной продукции');
INSERT INTO nc_land_category (id, code, name) VALUES (nextval('nc_land_category_seq'),'3001000030','Прочие земли сельскохозяйственного назначения');
INSERT INTO nc_land_category (id, code, name) VALUES (nextval('nc_land_category_seq'),'3002000000','ЗЕМЛИ НАСЕЛЕННЫХ ПУНКТОВ');
INSERT INTO nc_land_category (id, code, name) VALUES (nextval('nc_land_category_seq'),'3002000010','Земли в пределах населенных пунктов, отнесенные к территориальным зонам сельскохозяйственного использования');
INSERT INTO nc_land_category (id, code, name) VALUES (nextval('nc_land_category_seq'),'3002000020','Земельные участки, занятые жилищным фондом и объектами инженерной инфраструктуры жилищно-коммунального комплекса');
INSERT INTO nc_land_category (id, code, name) VALUES (nextval('nc_land_category_seq'),'3002000030','Земельные участки, предоставленные для жилищного строительства Земельные участки, приобретенные в собственность юридическими и физическими лицами на условиях осуществления на них жилищного строительства (за исключением индивидуального жилищного строительства)');
INSERT INTO nc_land_category (id, code, name) VALUES (nextval('nc_land_category_seq'),'3002000050','Земельные участки, приобретенные в собственность физическими лицами на условиях осуществления на них индивидуального жилищного строительства');
INSERT INTO nc_land_category (id, code, name) VALUES (nextval('nc_land_category_seq'),'3002000060','Земельные участки, предоставленные для ведения личного подсобного хозяйства, садоводства и огородничества или животноводства, а также дачного хозяйства');
INSERT INTO nc_land_category (id, code, name) VALUES (nextval('nc_land_category_seq'),'3002000070','Земельные участки, предоставленные юридическим лицам дляведения садоводства и огородничества или животноводства, а также дачного хозяйства');
INSERT INTO nc_land_category (id, code, name) VALUES (nextval('nc_land_category_seq'),'3002000080','Земельные участки, предоставленные физическим лицам для личного подсобного хозяйства, садоводства и огородничества или животноводства, а также дачного хозяйства');
INSERT INTO nc_land_category (id, code, name) VALUES (nextval('nc_land_category_seq'),'3002000090','Земли в пределах населенных пунктов, отнесенные к производственным территориальным зонам и зонам инженерных и транспортных инфраструктур');
INSERT INTO nc_land_category (id, code, name) VALUES (nextval('nc_land_category_seq'),'3002000100','Прочие земельные участки');
INSERT INTO nc_land_category (id, code, name) VALUES (nextval('nc_land_category_seq'),'3003000000','ЗЕМЛИ ПРОМЫШЛЕННОСТИ, ЭНЕРГЕТИКИ, ТРАНСПОРТА, СВЯЗИ, РАДИОВЕЩАНИЯ, ТЕЛЕВИДЕНИЯ, ИНФОРМАТИКИ, ЗЕМЛИ ДЛЯ ОБЕСПЕЧЕНИЯ КОСМИЧЕСКОЙ ДЕЯТЕЛЬНОСТИ, ЗЕМЛИ ОБОРОНЫ, БЕЗОПАСНОСТИ И ЗЕМЛИ ИНОГО СПЕЦИАЛЬНОГО НАЗНАЧЕНИЯ');
INSERT INTO nc_land_category (id, code, name) VALUES (nextval('nc_land_category_seq'),'3003000010','Земли промышленности');
INSERT INTO nc_land_category (id, code, name) VALUES (nextval('nc_land_category_seq'),'3003000020','Земли энергетики');
INSERT INTO nc_land_category (id, code, name) VALUES (nextval('nc_land_category_seq'),'3003000030','Земли транспорта');
INSERT INTO nc_land_category (id, code, name) VALUES (nextval('nc_land_category_seq'),'3003000040','Земли связи, радиовещания, телевидения, информатики');
INSERT INTO nc_land_category (id, code, name) VALUES (nextval('nc_land_category_seq'),'3003000050','Прочие земли');
INSERT INTO nc_land_category (id, code, name) VALUES (nextval('nc_land_category_seq'),'3004000000','ЗЕМЛИ ОСОБО ОХРАНЯЕМЫХ ТЕРРИТОРИЙ И ОБЪЕКТОВ');
INSERT INTO nc_land_category (id, code, name) VALUES (nextval('nc_land_category_seq'),'3005000000','ЗЕМЛИ ЛЕСНОГО ФОНДА');
INSERT INTO nc_land_category (id, code, name) VALUES (nextval('nc_land_category_seq'),'3006000000','ЗЕМЛИ ВОДНОГО ФОНДА');
INSERT INTO nc_land_category (id, code, name) VALUES (nextval('nc_land_category_seq'),'3007000000','ЗЕМЛИ ЗАПАСА');
INSERT INTO nc_land_category (id, code, name) VALUES (nextval('nc_land_category_seq'),'3008000000','Категория не установлена');
INSERT INTO nc_land_category (id, code, name) VALUES (nextval('nc_land_category_seq'),'0','Неопределено');
