INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '1000000', 'Государственная власть в Российской Федерации.\nДругие государственные органы Российской Федерации.\nЦентральный банк Российской Федерации', '');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '1100000', 'Президент Российской Федерации', '');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '1100001', 'Совет Безопасности Российской  Федерации', '');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '1100002', 'Администрация Президента Российской Федерации', '');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '1100003', 'Государственный совет Российской Федерации', '');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '1200000', 'Законодательная  власть в Российской Федерации', '');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '1200100', 'Федеральное Собрание Российской Федерации', '');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '1200101', 'Совет Федерации Федерального Собрания Российской Федерации', '');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '1200102', 'Государственная Дума Федерального Собрания Российской Федерации', '');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '1300000', 'Исполнительная власть в Российской Федерации', '');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '1300001', 'Правительство Российской Федерации', '');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '1310000', 'Федеральные министерства, федеральные службы и федеральные агентства, руководство деятельностью которых осуществляет Президент Российской Федерации, федеральные службы и федеральные агентства, подведомственные этим федеральным министерствам', '');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '1310500', 'Министерство внутренних дел Российской Федерации,МВД России', '');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '1310510', 'Федеральная миграционная служба,ФМС России', '');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '1311500', 'Министерство Российской Федерации по делам гражданской обороны, чрезвычайным ситуациям и ликвидации последствий стихийных бедствий', 'МЧС России');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '1312000', 'Министерство иностранных дел Российской Федерации,МИД России', '');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '1312055', 'Федеральное агентство по делам Содружества Независимых Государств, соотечественников, проживающих за рубежом, и по международному гуманитарному сотрудничеству', 'Россотрудничество');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '1313500', 'Министерство обороны Российской Федерации,Минобороны России', '');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '1313505', 'Федеральная служба по военно-техническому сотрудничеству', 'ФСВТС России');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '1313515', 'Федеральная служба по оборонному заказу', 'Рособоронзаказ');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '1313520', 'Федеральная служба по техническому и экспортному контролю', 'ФСТЭК России');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '1313565', 'Федеральное агентство по поставкам вооружения, военной, специальной техники и материальных средств', 'Рособоронпоставка');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '1313570', 'Федеральное агентство специального строительства', 'Спецстрой России');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '1318000', 'Министерство юстиции Российской Федерации', 'Минюст России');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '1318010', 'Федеральная служба исполнения наказаний', 'ФСИН России');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '1318025', 'Федеральная служба судебных приставов', 'ФССП России');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '1319805', 'Государственная фельдъегерская служба Российской Федерации (федеральная служба)', 'ГФС России');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '1319810', 'Служба внешней разведки Российской Федерации (федеральная служба)', 'СВР России');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '1319815', 'Федеральная служба безопасности Российской Федерации (федеральная служба)', 'ФСБ России');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '1319820', 'Федеральная служба Российской Федерации по контролю за оборотом наркотиков (федеральная служба)', 'ФСКН России');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '1319825', 'Федеральная служба охраны Российской Федерации (федеральная служба)', 'ФСО России');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '1319905', 'Главное управление специальных программ Президента Российской Федерации (федеральное агентство)', 'ГУСП');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '1319920', 'Управление делами Президента Российской Федерации (федеральное агентство)', '');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '1320000', 'Федеральные министерства, руководство деятельностью которых осуществляет Правительство Российской Федерации, федеральные службы и федеральные агентства, подведомственные этим федеральным министерствам"', '');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '1320500', 'Министерство здравоохранения и социального развития Российской Федерации', 'Минздравсоцразвития России');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '1320505', 'Федеральная служба по надзору в сфере защиты прав потребителей и благополучия человека', 'Роспотребнадзор');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '1320508', 'Федеральная служба по надзору в сфере здравоохранения и социального развития', 'Росздравнадзор');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '1320530', 'Федеральная служба по труду и занятости', 'Роструд');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '1320560', 'Федеральное медико-биологическое агентство', 'ФМБА России');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '1321000', 'Министерство культуры Российской Федерации', 'Минкультуры России');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '1321055', 'Федеральное архивное агентство', 'Росархив');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '1322500', 'Министерство образования и науки Российской Федерации', 'Минобрнауки России');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '1322505', 'Федеральная служба по интеллектуальной собственности, патентам и товарным знакам', 'Роспатент');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '1322520', 'Федеральная служба по надзору в сфере образования и науки', 'Рособрнадзор');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '1323000', 'Министерство природных ресурсов и экологии Российской Федерации', 'Минприроды России');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '1323005', 'Федеральная служба по гидрометеорологии и мониторингу окружающей среды', 'Росгидромет');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '1323020', 'Федеральная служба по надзору в сфере природопользования', 'Росприроднадзор');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '1323055', 'Федеральное агентство водных ресурсов', 'Росводресурсы');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '1323065', 'Федеральное агентство по недропользованию', 'Роснедра');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '1323500', 'Министерство промышленности и торговли Российской Федерации', 'Минпромторг России');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '1323565', 'Федеральное агентство по техническому регулированию и метрологии', 'Росстандарт');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '1324000', 'Министерство регионального развития Российской Федерации', 'Минрегион России');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '1324500', 'Министерство связи и массовых коммуникаций Российской Федерации', 'Минкомсвязь России');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '1324525', 'Федеральная служба по надзору в сфере связи, информационных технологий и массовых коммуникаций', 'Роскомнадзор');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '1324570', 'Федеральное агентство по печати и массовым коммуникациям', 'Роспечать');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '1324575', 'Федеральное агентство связи', 'Россвязь');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '1325000', 'Министерство сельского хозяйства Российской Федерации', 'Минсельхоз России');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '1325005', 'Федеральная служба по ветеринарному и фитосанитарному надзору', 'Россельхознадзор');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '1325500', 'Министерство спорта, туризма и молодежной политики Российской Федерации', 'Минспорттуризм России');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '1325555', 'Федеральное агентство по делам молодежи', 'Росмолодежь');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '1325570', 'Федеральное агентство по туризму', 'Ростуризм');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '1326000', 'Министерство транспорта Российской Федерации', 'Минтранс России');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '1326030', 'Федеральная служба по надзору в сфере транспорта', 'Ространснадзор');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '1326055', 'Федеральное агентство воздушного транспорта', 'Росавиация');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '1326060', 'Федеральное дорожное агентство', 'Росавтодор');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '1326065', 'Федеральное агентство железнодорожного транспорта', 'Росжелдор');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '1326080', 'Федеральное агентство морского и речного транспорта', 'Росморречфлот');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '1327000', 'Министерство финансов Российской Федерации', 'Минфин России');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '1327010', 'Федеральная налоговая служба', 'ФНС России');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '1327030', 'Федеральная служба финансово-бюджетного надзора', 'Росфиннадзор');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '1327035', 'Федеральное казначейство (федеральная служба)', 'Казначейство России');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '1328000', 'Министерство экономического развития Российской Федерации', 'Минэкономразвития России');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '1328005', 'Федеральная служба по аккредитации', '');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '1328010', 'Федеральная служба государственной статистики', 'Росстат');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '1328030', 'Федеральная служба государственной регистрации, кадастра и картографии', 'Росреестр');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '1328060', 'Федеральное агентство по государственным резервам', 'Росрезерв');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '1328080', 'Федеральное агентство по управлению государственным имуществом', 'Росимущество');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '1328500', 'Министерство энергетики Российской Федерации', 'Минэнерго России');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '1330000', 'Федеральные службы и федеральные агентства, руководство деятельностью которых осуществляет Правительство Российской Федерации', '');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '1330405', 'Федеральная антимонопольная служба', 'ФАС России');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '1330430', 'Федеральная таможенная служба', 'ФТС России');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '1330435', 'Федеральная служба по тарифам', 'ФСТ России');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '1330440', 'Федеральная служба по финансовому мониторингу', 'Росфинмониторинг');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '1330445', 'Федеральная служба по финансовым рынкам', 'ФСФР России');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '1330450', 'Федеральная служба по регулированию алкогольного рынка', 'Росалкогольрегулирование');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '1330455', 'Федеральная служба по экологическому, технологическому и атомному надзору', 'Ростехнадзор');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '1330610', 'Федеральное космическое агентство', 'Роскосмос');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '1330615', 'Федеральное агентство по обустройству государственной границы Российской Федерации', 'Росграница');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '1330620', 'Федеральное агентство по рыболовству', 'Росрыболовство');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '1330625', 'Федеральное агентство лесного хозяйства', 'Рослесхоз');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '1400000', 'Судебная власть в Российской Федерации', '');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '1400010', 'Конституционный суд Российской Федерации', '');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '1400020', 'Система федеральных судов общей юрисдикции', '');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '1400025', 'Система Судебного департамента при Верховном Суде Российской Федерации', '');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '1400030', 'Система федеральных арбитражных судов Российской Федерации', '');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '1400040', 'Система прокуратуры Российской Федерации', '');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '1400050', 'Следственный комитет Российской Федерации', '');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '1500000', 'Другие государственные органы Российской Федерации.\nЦентральный банк Российской Федерации', '');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '1500002', 'Счетная палата Российской Федерации', '');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '1500003', 'Центральная избирательная комиссия Российской Федерации', 'ЦИК России');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '1500004', 'Уполномоченный по правам человека в Российской Федерации', '');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '1500010', 'Центральный банк Российской Федерации', 'Банк России');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '2000000', 'Государственная власть в субъектах Российской Федерации.\nДругие государственные органы субъектов Российской Федерации', '');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '2100000', 'Высшее должностное лицо субъекта Российской Федерации', '');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '2200000', 'Законодательная (представительная)  власть  субъектов Российской Федерации', '');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '2300000', 'Исполнительная власть  субъектов Российской Федерации', '');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '2300001', 'Правительства (Администрации) субъектов Российской Федерации', '');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '2300200', 'Органы исполнительной власти субъектов Российской Федерации', '');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '2300215', 'Органы исполнительной власти субъектов Российской Федерации, осуществляющие функции в области/ финансирования', '');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '2300216', '- экономики', '');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '2300217', '- промышленности и торговли', '');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '2300219', '- сельского хозяйства', '');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '2300220', '- труда и  социальных вопросов', '');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '2300223', '- образования и науки', '');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '2300225', '- физической культуры и спорта', '');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '2300227', '- предупреждения и ликвидации последствий стихийных бедствий', '');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '2300228', '- охраны окружающей среды', '');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '2300229', '- здравоохранения', '');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '2300230', '- жилищно-коммунального хозяйства', '');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '2300231', '- культуры', '');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '2300232', '- связи и средств массовой информации', '');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '2300234', '- транспорта и дорожного строительства', '');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '2300236', '- архитектуры и строительства', '');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '2300280', 'Органы исполнительной власти  субъектов Российской Федерации, осуществляющие другие функции', '');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '2400000', 'Органы судебной власти субъектов Российской Федерации', '');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '2400100', 'Конституционные (уставные) суды  субъектов Российской Федерации', '');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '2400400', 'Мировые судьи', '');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '2500000', 'Другие государственные органы  субъектов Российской Федерации', '');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '2500030', 'Уполномоченные по правам человека  субъектов Российской Федерации', '');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '2500040', 'Контрольные органы  субъектов Российской Федерации', '');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '2500050', 'Избирательные комиссии субъектов Российской Федерации', '');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '3000000', 'Местное самоуправление в Российской Федерации.\nИзбирательные комиссии муниципальных образований', '');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '3200000', 'Представительные органы муниципальных образований', '');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '3200100', 'Представительные органы муниципальных районов', '');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '3200200', 'Представительные органы городских округов', '');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '3200300', 'Представительные органы внутригородских территорий городов федерального значения', '');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '3200400', 'Представительные органы городских поселений', '');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '3200500', 'Представительные органы сельских поселений', '');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '3300000', 'Местные администрации (исполнительно-распорядительные органы муниципальных образований)', '');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '3300100', 'Местные администрации (исполнительно-распорядительные органы) муниципальных районов', '');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '3300200', 'Местные администрации (исполнительно-распорядительные органы) городских округов', '');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '3300300', 'Местные администрации (исполнительно-распорядительные органы) внутригородских территорий городов федерального значения', '');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '3300400', 'Местные администрации (исполнительно-распорядительные органы) городских поселений', '');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '3300500', 'Местные администрации (исполнительно-распорядительные органы) сельских поселений', '');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '3400000', 'Контрольные органы муниципальных образований', '');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '3400100', 'Контрольные органы муниципальных районов', '');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '3400200', 'Контрольные органы городских округов', '');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '3400300', 'Контрольные органы внутригородских территорий городов федерального значения', '');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '3400400', 'Контрольные органы городских поселений', '');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '3400500', 'Контрольные органы сельских поселений', '');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '3500000', 'Иные органы местного самоуправления', '');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '3500100', 'Иные органы муниципальных районов', '');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '3500200', 'Иные органы городских округов', '');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '3500300', 'Иные органы внутригородских территорий городов федерального значения', '');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '3500400', 'Иные органы городских поселений', '');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '3500500', 'Иные органы сельских поселений', '');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '3900000', 'Избирательные комиссии муниципальных образований', '');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '3900100', 'Избирательные комиссии муниципальных районов', '');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '3900200', 'Избирательные комиссии городских округов', '');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '3900300', 'Избирательные комиссии внутригородских территорий городов федерального значения', '');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '3900400', 'Избирательные комиссии городских поселений', '');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '3900500', 'Избирательные комиссии сельских поселений', '');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '4000000', 'Организации, по которым осуществляется федеральное статистическое наблюдение\nГруппировки хозяйствующих субъектов и общественных объединений, используемые для официального статистического учета', '');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '4100000', 'Организации, по которым осуществляется федеральное статистическое наблюдение', '');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '4100100', 'Банки', '');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '4100102', 'Банк ВТБ (открытое акционерное общество)', 'ОАО Банк ВТБ');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '4100103', 'Государственная корпорация "Банк развития и внешнеэкономической деятельности (Внешэкономбанк)', 'Внешэкономбанк');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '4100104', 'Открытое акционерное общество "Сбербанк России"', '"ОАО "Сбербанк России"');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '4100200', 'Фонды', '');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '4100201', 'Пенсионный фонд Российской Федерации', 'ПФР');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '4100202', 'Федеральный фонд обязательного медицинского страхования', 'ФОМС');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '4100203', 'Фонд социального страхования Российской Федерации', 'ФСС');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '4100204', 'Российский гуманитарный научный фонд', 'РГНФ');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '4100205', 'Российский фонд фундаментальных исследований', '');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '4100206', 'Фонд содействия развитию малых форм предприятий в научно-технической сфере', '');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '4100207', 'Федеральный фонд содействия развитию жилищного строительства,Фонд «РЖС»', '');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '4100300', 'Государственные корпорации', '');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '4100301', 'Государственная корпорация по атомной энергии "Росатом","Госкорпорация "Росатом"', '');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '4100303', 'Государственная корпорация по строительству олимпийских объектов и развитию города Сочи как горноклиматического курорта', 'ГК «Олимпстрой»');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '4100304', 'Государственная корпорация по содействию разработке, производству и экспорту высокотехнологичной промышленной продукции "Ростехнологии"', 'Государственная корпорация "Ростехнологии"');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '4100305', 'Агентство по страхованию вкладов', '');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '4100306', 'Фонд содействия реформированию жилищно-коммунального хозяйства', '');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '4100400', 'Государственные компании', '');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '4100401', 'Государственная компания «Российские автомобильные дороги»', 'Государственная компания «Автодор»');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '4100500', 'Российские академии', '');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '4100501', 'Российская академия наук', 'РАН');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '4100502', 'Российская академия сельскохозяйственных наук', 'Россельхозакадемия');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '4100503', 'Российская академия медицинских наук', 'РАМН');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '4100504', 'Российская академия архитектуры и строительных наук', 'Росархстройакадемия');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '4100505', 'Российская академия образования', 'РАО');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '4100506', 'Российская академия художеств', '');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '4100600', 'Акционерные общества', '');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '4100601', 'Открытое акционерное общество "Газпром"', '"ОАО "Газпром"');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '4100602', 'Открытое акционерное общество "Российская агрохимическая компания', 'ОАО Росагрохим');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '4100603', 'Открытое акционерное общество "БИОПРЕПАРАТ"', 'ОАО "БИОПРЕПАРАТ"');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '4100604', 'Акционерное общество открытого типа "Концерн "ДеКО"', 'АО "Концерн ДеКО"');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '4100605', 'Открытое акционерное общество "Российская государственная страховая компания"', 'ОАО "Росгосстрах"');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '4100606', 'Открытое акционерное общество "Федеральная контрактная корпорация "РОСКОНТРАКТ"', 'ОАО "ФКК "Росконтракт"');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '4100607', 'Открытое акционерное общество "Российская топливная компания" – Ростоппром"', 'ОАО "Ростоппром"');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '4100608', 'Открытое акционерное общество Российская автотранспортная  компания "Росавтотранс"', 'РАО "Росавтотранс", ОАО"');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '4100609', 'Открытое акционерное общество "Государственное акционерное общество "Всероссийский выставочный центр"', 'ОАО "ГАО ВВЦ"');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '4100610', 'Открытое акционерное общество "Россевзапстрой"', 'ОАО "Россевзапстрой"');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '4100612', 'Открытое акционерное общество "Российские железные дороги"', 'ОАО "РЖД"');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '4100613', 'Открытое акционерное общество "Московский концерн по производству продукции текстильной промышленности "Мостекс"', 'ОАО "Концерн "Мостекс"');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '4100614', 'Открытое акционерное общество "Нефтяная компания "Роснефть"', 'ОАО "НК "Роснефть"');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '4100615', 'Открытое акционерное общество "Нефтяная компания "ЛУКОЙЛ"', 'ОАО "ЛУКОЙЛ"');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '4100617', 'Открытое акционерное общество "Акционерная компания по транспорту нефти "Транснефть"', '"ОАО "АК "Транснефть"');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '4100618', 'Открытое акционерное общество "Акционерная компания трубопроводного транспорта нефтепродуктов "Транснефтепродукт"', '"ОАО "АК "Транснефтепродукт"');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '4100622', 'Открытое акционерное общество "Газпром нефть"', '"ОАО "Газпром нефть"');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '4100623', 'Открытое акционерное общество "РОСНАНО"', 'ОАО "РОСНАНО"');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '4100900', 'Другие организации,  по которым осуществляется федеральное статистическое наблюдение', '');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '4100901', 'Общественная палата Российской Федерации', '');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '4100902', 'Межреспубликанская ассоциация учебных заведений по подготовке и переподготовке кадров машиностроения "Машиностроитель"', 'АУЗМАШ');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '4100903', 'Центральный союз потребительских обществ Российской Федерации', 'Центросоюз Российской Федерации');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '4200000', 'Группировки хозяйствующих субъектов и общественных объединений, используемые для официального статистического учета', '');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '4210000', 'Группировки хозяйствующих субъектов', '');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '4210001', 'Хозяйственные общества, образованные из  государственных  предприятий, добровольных объединений государственных предприятий', '');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '4210004', 'Акционерные общества, товарищества, сельскохозяйственные производственные кооперативы, образованные при реорганизации колхозов и совхозов и приватизации отдельных сельскохозяйственных предприятий', '');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '4210005', 'Крестьянские (фермерские) хозяйства', '');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '4210007', 'Муниципальные организации', '');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '4210008', 'Приватизированные предприятия', '');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '4210009', 'Иностранные юридические лица и их представительства, осуществляющие деятельность на территории Российской Федерации (кроме некоммерческих неправительственных организаций)', '');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '4210011', 'Хозяйственные общества и товарищества с участием иностранных юридических и (или) физических лиц, а также лиц без гражданства', '');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '4210012', 'Представительства (посольства) иностранных государств, иные представительства органов управления иностранных государств, отделения, филиалы, представительства иностранных некоммерческих неправительственных организаций', '');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '4210014', 'Организации, учрежденные юридическими лицами или гражданами, или юридическими лицами и гражданами совместно', '');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '4210015', 'Индивидуальные предприниматели', '');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '4210020', 'Казачьи общества, созданные в форме некоммерческой организации и внесенные  в государственный реестр казачьих обществ в Российской Федерации', '');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '4210021', 'Добровольные объединения (ассоциации) экономического взаимодействия субъектов Российской Федерации, органов местного самоуправления', '');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '4210090', 'Другие хозяйствующие субъекты', '');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '4220000', 'Общественные объединения', '');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '4220001', 'Общероссийские общественные объединения', '');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '4220002', 'Межрегиональные общественные объединения', '');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '4220003', 'Региональные и местные общественные объединения', '');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '4220004', 'Международные общественные объединения', '');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '5000000', 'Межгосударственные органы управления', '');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '5100000', 'Межгосударственные органы управления, образованные странами с участием Российской Федерации', '');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '5100001', 'Межгосударственный авиационный комитет – исполнительный орган Содружества Независимых Государств', 'МАК');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '5100002', 'Комитет по делам воинов-интернационалистов при Совете глав правительств государств - участников Содружества,Комитет по делам воинов-интернационалистов при СГП СНГ', '');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '5100003', 'Электроэнергетический совет Содружества Независимых Государств', '');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '5100004', 'Межгосударственный банк', '');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '5100006', 'Межгосударственное евроазиатское объединение угля и металла', 'МЕАОУМ');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '5100007', 'Исполнительный комитет Содружества Независимых Государств', 'Исполнительный комитет СНГ');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '5100009', 'Главное командование объединенных вооруженных сил СНГ', '');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '5100011', 'Межгосударственный статистический комитет Содружества Независимых Государств', 'Статкомитет СНГ');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '5100013', 'Международный банк экономического сотрудничества', 'МБЭС');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '5100014', 'Международный инвестиционный банк', 'МИБ');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '5100015', 'Межправительственный совет по нефти и газу', '');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '5100018', 'Организация Договора о коллективной безопасности', 'ОДКБ');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '5100019', 'Исполнительный комитет Союза Беларуси и России', '');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '5100021', 'Координационный совет генеральных прокуроров государств-участников Содружества Независимых Государств', '');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '5100022', 'Евразийское экономическое сообщество', 'ЕврАзЭС');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '5100023', 'Таможенный союз ЕврАзЭС', '');
INSERT INTO nc_okogu (id, code, name, comment) VALUES (nextval('nc_okogu_seq'), '5100029', 'Шанхайская организация сотрудничества', 'ШОС');
