insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'1 00 00',	'ОРГАНИЗАЦИОННО-ПРАВОВЫЕ ФОРМЫ ЮРИДИЧЕСКИХ ЛИЦ,	ЯВЛЯЮЩИХСЯ КОММЕРЧЕСКИМИ КОРПОРАТИВНЫМИ ОРГАНИЗАЦИЯМИ');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'1 10 00',	'Хозяйственные товарищества');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'1 10 51',	'Полные товарищества');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'1 10 64',	'Товарищества на вере (коммандитные товарищества)');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'1 20 00',	'Хозяйственные общества');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'1 22 00',	'Акционерные общества');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'1 22 47',	'Публичные акционерные общества');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'1 22 67',	'Непубличные акционерные общества');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'1 23 00',	'Общества с ограниченной ответственностью');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'1 30 00',	'Хозяйственные партнерства');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'1 40 00',	'Производственные кооперативы (артели)');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'1 41 00',	'Сельскохозяйственные производственные кооперативы');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'1 41 53',	'Сельскохозяйственные артели (колхозы)');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'1 41 54',	'Рыболовецкие артели (колхозы)');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'1 41 55',	'Кооперативные хозяйства (коопхозы)');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'1 42 00',	'Производственные кооперативы (кроме сельскохозяйственных производственных кооперативов)');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'1 53 00',	'Крестьянские (фермерские) хозяйства');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'1 90 00',	'Прочие юридические лица, являющиеся коммерческими организациями');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'2 00 00',	'ОРГАНИЗАЦИОННО-ПРАВОВЫЕ ФОРМЫ ЮРИДИЧЕСКИХ ЛИЦ,	ЯВЛЯЮЩИХСЯ НЕКОММЕРЧЕСКИМИ КОРПОРАТИВНЫМИ ОРГАНИЗАЦИЯМИ');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'2 01 00',	'Потребительские кооперативы');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'2 01 01',	'Гаражные и гаражно-строительные кооперативы');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'2 01 02',	'Жилищные или жилищно-строительные кооперативы');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'2 01 03',	'Жилищные накопительные кооперативы');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'2 01 04',	'Кредитные потребительские кооперативы');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'2 01 05',	'Кредитные потребительские кооперативы граждан');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'2 01 06',	'Кредитные кооперативы второго уровня');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'2 01 07',	'Потребительские общества');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'2 01 08',	'Общества взаимного страхования');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'2 01 09',	'Сельскохозяйственные потребительские перерабатывающие кооперативы');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'2 01 10',	'Сельскохозяйственные потребительские сбытовые (торговые) кооперативы');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'2 01 11',	'Сельскохозяйственные потребительские обслуживающие кооперативы');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'2 01 12',	'Сельскохозяйственные потребительские снабженческие кооперативы');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'2 01 13',	'Сельскохозяйственные потребительские садоводческие кооперативы');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'2 01 14',	'Сельскохозяйственные потребительские огороднические кооперативы');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'2 01 15',	'Сельскохозяйственные потребительские животноводческие кооперативы');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'2 01 20',	'Садоводческие, огороднические или дачные потребительские кооперативы');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'2 01 21',	'Фонды проката');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'2 02 00',	'Общественные организации');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'2 02 01',	'Политические партии');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'2 02 02',	'Профсоюзные организации');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'2 02 10',	'Общественные движения');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'2 02 11',	'Органы общественной самодеятельности');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'2 02 17',	'Территориальные общественные самоуправления');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'2 06 00',	'Ассоциации (союзы)');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'2 06 01',	'Ассоциации (союзы) экономического взаимодействия субъектов Российской Федерации');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'2 06 03',	'Советы муниципальных образований субъектов Российской Федерации');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'2 06 04',	'Союзы (ассоциации) кредитных кооперативов');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'2 06 05',	'Союзы (ассоциации) кооперативов');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'2 06 06',	'Союзы (ассоциации) общественных объединений');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'2 06 07',	'Союзы (ассоциации) общин малочисленных народов');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'2 06 08',	'Союзы потребительских обществ');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'2 06 09',	'Адвокатские палаты');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'2 06 10',	'Нотариальные палаты');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'2 06 11',	'Торгово-промышленные палаты');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'2 06 12',	'Объединения работодателей');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'2 06 13',	'Объединения фермерских хозяйств');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'2 06 14',	'Некоммерческие партнерства');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'2 06 15',	'Адвокатские бюро');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'2 06 16',	'Коллегии адвокатов');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'2 06 17',	'Садоводческие, огороднические или дачные некоммерческие партнерства');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'2 06 18',	'Ассоциации (союзы) садоводческих, огороднических и дачных некоммерческих объединений');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'2 06 19',	'Саморегулируемые организации');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'2 06 20',	'Объединения (ассоциации и союзы) благотворительных организаций');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'2 07 00',	'Товарищества собственников недвижимости');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'2 07 01',	'Садоводческие, огороднические или дачные некоммерческие товарищества');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'2 07 16',	'Товарищества собственников жилья');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'2 11 00',	'Казачьи общества, внесенные в государственный реестр казачьих обществ в Российской Федерации');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'2 12 00',	'Общины коренных малочисленных народов Российской Федерации');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'3 00 00',	'ОРГАНИЗАЦИОННО-ПРАВОВЫЕ ФОРМЫ ОРГАНИЗАЦИЙ, СОЗДАННЫХ БЕЗ ПРАВ ЮРИДИЧЕСКОГО ЛИЦА');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'3 00 01',	'Представительства юридических лиц');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'3 00 02',	'Филиалы юридических лиц');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'3 00 03',	'Обособленные подразделения юридических лиц');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'3 00 04',	'Структурные подразделения обособленных подразделений юридических лиц');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'3 00 05',	'Паевые инвестиционные фонды');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'3 00 06',	'Простые товарищества');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'3 00 08',	'Районные суды, городские суды, межрайонные суды (районные суды)');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'4 00 00',	'ОРГАНИЗАЦИОННО-ПРАВОВЫЕ ФОРМЫ МЕЖДУНАРОДНЫХ ОРГАНИЗАЦИЙ, ОСУЩЕСТВЛЯЮЩИХ ДЕЯТЕЛЬНОСТЬ НА ТЕРРИТОРИИ РОССИЙСКОЙ ФЕДЕРАЦИИ');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'4 00 01',	'Межправительственные международные организации');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'4 00 02',	'Неправительственные международные организации');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'5 00 00',	'ОРГАНИЗАЦИОННО-ПРАВОВЫЕ ФОРМЫ ДЛЯ ДЕЯТЕЛЬНОСТИ ГРАЖДАН (ФИЗИЧЕСКИХ ЛИЦ)');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'5 01 00',	'Организационно-правовые формы для коммерческой деятельности граждан');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'5 01 01',	'Главы крестьянских (фермерских) хозяйств');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'5 01 02',	'Индивидуальные предприниматели');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'5 02 00',	'Организационно-правовые формы для деятельности граждан, не отнесенной к предпринимательству');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'5 02 01',	'Адвокаты, учредившие адвокатский кабинет');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'5 02 02',	'Нотариусы, занимающиеся частной практикой');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'6 00 00',	'ОРГАНИЗАЦИОННО-ПРАВОВЫЕ ФОРМЫ ЮРИДИЧЕСКИХ ЛИЦ, ЯВЛЯЮЩИХСЯ КОММЕРЧЕСКИМИ УНИТАРНЫМИ ОРГАНИЗАЦИЯМИ');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'6 50 00',	'Унитарные предприятия');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'6 51 00',	'Унитарные предприятия, основанные на праве оперативного управления (казенные предприятия)');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'6 51 41',	'Федеральные казенные предприятия');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'6 51 42',	'Казенные предприятия субъектов Российской Федерации');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'6 51 43',	'Муниципальные казенные предприятия');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'6 52 00',	'Унитарные предприятия, основанные на праве хозяйственного ведения');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'6 52 41',	'Федеральные государственные унитарные предприятия');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'6 52 42',	'Государственные унитарные предприятия субъектов Российской Федерации');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'6 52 43',	'Муниципальные унитарные предприятия');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'7 00 00',	'ОРГАНИЗАЦИОННО-ПРАВОВЫЕ ФОРМЫ ЮРИДИЧЕСКИХ ЛИЦ, ЯВЛЯЮЩИХСЯ НЕКОММЕРЧЕСКИМИ УНИТАРНЫМИ ОРГАНИЗАЦИЯМИ');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'7 04 00',	'Фонды');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'7 04 01',	'Благотворительные фонды');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'7 04 02',	'Негосударственные пенсионные фонды');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'7 04 03',	'Общественные фонды');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'7 04 04',	'Экологические фонды');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'7 14 00',	'Автономные некоммерческие организации');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'7 15 00',	'Религиозные организации');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'7 16 00',	'Публично-правовые компании');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'7 16 01',	'Государственные корпорации');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'7 16 02',	'Государственные компании');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'7 16 10',	'Отделения иностранных некоммерческих неправительственных организаций');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'7 50 00',	'Учреждения');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'7 51 00',	'Учреждения, созданные Российской Федерацией');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'7 51 01',	'Федеральные государственные автономные учреждения');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'7 51 03',	'Федеральные государственные бюджетные учреждения');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'7 51 04',	'Федеральные государственные казенные учреждения');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'7 52 00',	'Учреждения, созданные субъектом Российской Федерации');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'7 52 01',	'Государственные автономные учреждения субъектов Российской Федерации');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'7 52 03',	'Государственные бюджетные учреждения субъектов Российской Федерации');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'7 52 04',	'Государственные казенные учреждения субъектов Российской Федерации');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'7 53 00',	'Государственные академии наук');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'7 54 00',	'Учреждения, созданные муниципальным образованием (муниципальные учреждения)');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'7 54 01',	'Муниципальные автономные учреждения');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'7 54 03',	'Муниципальные бюджетные учреждения');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'7 54 04',	'Муниципальные казенные учреждения');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'7 55 00',	'Частные учреждения');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'7 55 02',	'Благотворительные учреждения');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'7 55 05',	'Общественные учреждения');
