insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'10000',	'ОРГАНИЗАЦИОННО-ПРАВОВЫЕ ФОРМЫ ЮРИДИЧЕСКИХ ЛИЦ,	ЯВЛЯЮЩИХСЯ КОММЕРЧЕСКИМИ КОРПОРАТИВНЫМИ ОРГАНИЗАЦИЯМИ');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'11000',	'Хозяйственные товарищества');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'11051',	'Полные товарищества');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'11064',	'Товарищества на вере (коммандитные товарищества)');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'12000',	'Хозяйственные общества');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'12200',	'Акционерные общества');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'12247',	'Публичные акционерные общества');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'12267',	'Непубличные акционерные общества');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'12300',	'Общества с ограниченной ответственностью');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'13000',	'Хозяйственные партнерства');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'14000',	'Производственные кооперативы (артели)');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'14100',	'Сельскохозяйственные производственные кооперативы');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'14153',	'Сельскохозяйственные артели (колхозы)');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'14154',	'Рыболовецкие артели (колхозы)');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'14155',	'Кооперативные хозяйства (коопхозы)');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'14200',	'Производственные кооперативы (кроме сельскохозяйственных производственных кооперативов)');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'15300',	'Крестьянские (фермерские) хозяйства');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'19000',	'Прочие юридические лица, являющиеся коммерческими организациями');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'20000',	'ОРГАНИЗАЦИОННО-ПРАВОВЫЕ ФОРМЫ ЮРИДИЧЕСКИХ ЛИЦ,	ЯВЛЯЮЩИХСЯ НЕКОММЕРЧЕСКИМИ КОРПОРАТИВНЫМИ ОРГАНИЗАЦИЯМИ');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'20100',	'Потребительские кооперативы');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'20101',	'Гаражные и гаражно-строительные кооперативы');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'20102',	'Жилищные или жилищно-строительные кооперативы');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'20103',	'Жилищные накопительные кооперативы');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'20104',	'Кредитные потребительские кооперативы');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'20105',	'Кредитные потребительские кооперативы граждан');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'20106',	'Кредитные кооперативы второго уровня');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'20107',	'Потребительские общества');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'20108',	'Общества взаимного страхования');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'20109',	'Сельскохозяйственные потребительские перерабатывающие кооперативы');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'20110',	'Сельскохозяйственные потребительские сбытовые (торговые) кооперативы');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'20111',	'Сельскохозяйственные потребительские обслуживающие кооперативы');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'20112',	'Сельскохозяйственные потребительские снабженческие кооперативы');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'20113',	'Сельскохозяйственные потребительские садоводческие кооперативы');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'20114',	'Сельскохозяйственные потребительские огороднические кооперативы');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'20115',	'Сельскохозяйственные потребительские животноводческие кооперативы');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'20120',	'Садоводческие, огороднические или дачные потребительские кооперативы');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'20121',	'Фонды проката');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'20200',	'Общественные организации');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'20201',	'Политические партии');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'20202',	'Профсоюзные организации');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'20210',	'Общественные движения');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'20211',	'Органы общественной самодеятельности');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'20217',	'Территориальные общественные самоуправления');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'20600',	'Ассоциации (союзы)');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'20601',	'Ассоциации (союзы) экономического взаимодействия субъектов Российской Федерации');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'20603',	'Советы муниципальных образований субъектов Российской Федерации');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'20604',	'Союзы (ассоциации) кредитных кооперативов');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'20605',	'Союзы (ассоциации) кооперативов');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'20606',	'Союзы (ассоциации) общественных объединений');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'20607',	'Союзы (ассоциации) общин малочисленных народов');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'20608',	'Союзы потребительских обществ');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'20609',	'Адвокатские палаты');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'20610',	'Нотариальные палаты');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'20611',	'Торгово-промышленные палаты');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'20612',	'Объединения работодателей');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'20613',	'Объединения фермерских хозяйств');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'20614',	'Некоммерческие партнерства');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'20615',	'Адвокатские бюро');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'20616',	'Коллегии адвокатов');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'20617',	'Садоводческие, огороднические или дачные некоммерческие партнерства');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'20618',	'Ассоциации (союзы) садоводческих, огороднических и дачных некоммерческих объединений');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'20619',	'Саморегулируемые организации');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'20620',	'Объединения (ассоциации и союзы) благотворительных организаций');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'20700',	'Товарищества собственников недвижимости');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'20701',	'Садоводческие, огороднические или дачные некоммерческие товарищества');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'20716',	'Товарищества собственников жилья');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'21100',	'Казачьи общества, внесенные в государственный реестр казачьих обществ в Российской Федерации');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'21200',	'Общины коренных малочисленных народов Российской Федерации');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'30000',	'ОРГАНИЗАЦИОННО-ПРАВОВЫЕ ФОРМЫ ОРГАНИЗАЦИЙ, СОЗДАННЫХ БЕЗ ПРАВ ЮРИДИЧЕСКОГО ЛИЦА');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'30001',	'Представительства юридических лиц');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'30002',	'Филиалы юридических лиц');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'30003',	'Обособленные подразделения юридических лиц');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'30004',	'Структурные подразделения обособленных подразделений юридических лиц');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'30005',	'Паевые инвестиционные фонды');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'30006',	'Простые товарищества');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'30008',	'Районные суды, городские суды, межрайонные суды (районные суды)');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'40000',	'ОРГАНИЗАЦИОННО-ПРАВОВЫЕ ФОРМЫ МЕЖДУНАРОДНЫХ ОРГАНИЗАЦИЙ, ОСУЩЕСТВЛЯЮЩИХ ДЕЯТЕЛЬНОСТЬ НА ТЕРРИТОРИИ РОССИЙСКОЙ ФЕДЕРАЦИИ');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'40001',	'Межправительственные международные организации');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'40002',	'Неправительственные международные организации');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'50000',	'ОРГАНИЗАЦИОННО-ПРАВОВЫЕ ФОРМЫ ДЛЯ ДЕЯТЕЛЬНОСТИ ГРАЖДАН (ФИЗИЧЕСКИХ ЛИЦ)');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'50100',	'Организационно-правовые формы для коммерческой деятельности граждан');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'50101',	'Главы крестьянских (фермерских) хозяйств');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'50102',	'Индивидуальные предприниматели');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'50200',	'Организационно-правовые формы для деятельности граждан, не отнесенной к предпринимательству');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'50201',	'Адвокаты, учредившие адвокатский кабинет');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'50202',	'Нотариусы, занимающиеся частной практикой');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'60000',	'ОРГАНИЗАЦИОННО-ПРАВОВЫЕ ФОРМЫ ЮРИДИЧЕСКИХ ЛИЦ, ЯВЛЯЮЩИХСЯ КОММЕРЧЕСКИМИ УНИТАРНЫМИ ОРГАНИЗАЦИЯМИ');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'65000',	'Унитарные предприятия');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'65100',	'Унитарные предприятия, основанные на праве оперативного управления (казенные предприятия)');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'65141',	'Федеральные казенные предприятия');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'65142',	'Казенные предприятия субъектов Российской Федерации');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'65143',	'Муниципальные казенные предприятия');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'65200',	'Унитарные предприятия, основанные на праве хозяйственного ведения');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'65241',	'Федеральные государственные унитарные предприятия');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'65242',	'Государственные унитарные предприятия субъектов Российской Федерации');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'65243',	'Муниципальные унитарные предприятия');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'70000',	'ОРГАНИЗАЦИОННО-ПРАВОВЫЕ ФОРМЫ ЮРИДИЧЕСКИХ ЛИЦ, ЯВЛЯЮЩИХСЯ НЕКОММЕРЧЕСКИМИ УНИТАРНЫМИ ОРГАНИЗАЦИЯМИ');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'70400',	'Фонды');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'70401',	'Благотворительные фонды');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'70402',	'Негосударственные пенсионные фонды');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'70403',	'Общественные фонды');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'70404',	'Экологические фонды');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'71400',	'Автономные некоммерческие организации');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'71500',	'Религиозные организации');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'71600',	'Публично-правовые компании');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'71601',	'Государственные корпорации');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'71602',	'Государственные компании');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'71610',	'Отделения иностранных некоммерческих неправительственных организаций');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'75000',	'Учреждения');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'75100',	'Учреждения, созданные Российской Федерацией');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'75101',	'Федеральные государственные автономные учреждения');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'75103',	'Федеральные государственные бюджетные учреждения');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'75104',	'Федеральные государственные казенные учреждения');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'75200',	'Учреждения, созданные субъектом Российской Федерации');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'75201',	'Государственные автономные учреждения субъектов Российской Федерации');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'75203',	'Государственные бюджетные учреждения субъектов Российской Федерации');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'75204',	'Государственные казенные учреждения субъектов Российской Федерации');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'75300',	'Государственные академии наук');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'75400',	'Учреждения, созданные муниципальным образованием (муниципальные учреждения)');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'75401',	'Муниципальные автономные учреждения');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'75403',	'Муниципальные бюджетные учреждения');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'75404',	'Муниципальные казенные учреждения');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'75500',	'Частные учреждения');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'75502',	'Благотворительные учреждения');
insert into nc_okopf (id,	code,	name) values (nextval('nc_okopf_seq'),	'75505',	'Общественные учреждения');
