TRUNCATE TABLE nc_oktmo;
INSERT INTO nc_oktmo (id, code, control_number, name, comment) VALUES (nextval('nc_oktmo_seq'), '79000000','3','Муниципальные образования Республики Адыгеи (Адыгеи)','');
INSERT INTO nc_oktmo (id, code, control_number, name, comment) VALUES (nextval('nc_oktmo_seq'), '79600000','0','Муниципальные районы Республики Адыгеи (Адыгеи)','');
INSERT INTO nc_oktmo (id, code, control_number, name, comment) VALUES (nextval('nc_oktmo_seq'), '79605000','2','Гиагинский муниципальный район','ст-ца Гиагинская');
INSERT INTO nc_oktmo (id, code, control_number, name, comment) VALUES (nextval('nc_oktmo_seq'), '79605400','4','Сельские поселения Гиагинского муниципального района/','');
INSERT INTO nc_oktmo (id, code, control_number, name, comment) VALUES (nextval('nc_oktmo_seq'), '79605402','9','- Айрюмовское','п Новый');
INSERT INTO nc_oktmo (id, code, control_number, name, comment) VALUES (nextval('nc_oktmo_seq'), '79605407','5','- Гиагинское','ст-ца Гиагинская');
INSERT INTO nc_oktmo (id, code, control_number, name, comment) VALUES (nextval('nc_oktmo_seq'), '79605410','0','- Дондуковское','ст-ца Дондуковская');
INSERT INTO nc_oktmo (id, code, control_number, name, comment) VALUES (nextval('nc_oktmo_seq'), '79605415','7','- Келермесское','ст-ца Келермесская');
INSERT INTO nc_oktmo (id, code, control_number, name, comment) VALUES (nextval('nc_oktmo_seq'), '79605420','7','- Сергиевское','с Сергиевское');
INSERT INTO nc_oktmo (id, code, control_number, name, comment) VALUES (nextval('nc_oktmo_seq'), '79615000','6','Кошехабльский муниципальный район','аул Кошехабль');
INSERT INTO nc_oktmo (id, code, control_number, name, comment) VALUES (nextval('nc_oktmo_seq'), '79615400','8','Сельские поселения Кошехабльского муниципального района/','');
INSERT INTO nc_oktmo (id, code, control_number, name, comment) VALUES (nextval('nc_oktmo_seq'), '79615404','7','- Блечепсинское','аул Блечепсин');
INSERT INTO nc_oktmo (id, code, control_number, name, comment) VALUES (nextval('nc_oktmo_seq'), '79615408','6','- Вольненское','с Вольное');
INSERT INTO nc_oktmo (id, code, control_number, name, comment) VALUES (nextval('nc_oktmo_seq'), '79615412','9','- Дмитриевское','п Дружба');
INSERT INTO nc_oktmo (id, code, control_number, name, comment) VALUES (nextval('nc_oktmo_seq'), '79615415','0','- Егерухайское','аул Егерухай');
INSERT INTO nc_oktmo (id, code, control_number, name, comment) VALUES (nextval('nc_oktmo_seq'), '79615418','2','- Игнатьевское','х Игнатьевский');
INSERT INTO nc_oktmo (id, code, control_number, name, comment) VALUES (nextval('nc_oktmo_seq'), '79615420','0','- Кошехабльское','аул Кошехабль');
INSERT INTO nc_oktmo (id, code, control_number, name, comment) VALUES (nextval('nc_oktmo_seq'), '79615425','7','- Майское','п Майский');
INSERT INTO nc_oktmo (id, code, control_number, name, comment) VALUES (nextval('nc_oktmo_seq'), '79615430','7','- Натырбовское','с Натырбово');
INSERT INTO nc_oktmo (id, code, control_number, name, comment) VALUES (nextval('nc_oktmo_seq'), '79615445','4','- Ходзинское','аул Ходзь');
INSERT INTO nc_oktmo (id, code, control_number, name, comment) VALUES (nextval('nc_oktmo_seq'), '79618000','6','Красногвардейский муниципальный район','с Красногвардейское');
INSERT INTO nc_oktmo (id, code, control_number, name, comment) VALUES (nextval('nc_oktmo_seq'), '79618400','1','Сельские поселения Красногвардейского муниципального района/','');
INSERT INTO nc_oktmo (id, code, control_number, name, comment) VALUES (nextval('nc_oktmo_seq'), '79618404','0','- Белосельское','с Белое');
INSERT INTO nc_oktmo (id, code, control_number, name, comment) VALUES (nextval('nc_oktmo_seq'), '79618408','8','- Большесидоровское','с Большесидоровское');
INSERT INTO nc_oktmo (id, code, control_number, name, comment) VALUES (nextval('nc_oktmo_seq'), '79618415','4','- Еленовское','с Еленовское');
INSERT INTO nc_oktmo (id, code, control_number, name, comment) VALUES (nextval('nc_oktmo_seq'), '79618420','4','- Красногвардейское','с Красногвардейское');
INSERT INTO nc_oktmo (id, code, control_number, name, comment) VALUES (nextval('nc_oktmo_seq'), '79618425','0','- Садовское','с Садовое');
INSERT INTO nc_oktmo (id, code, control_number, name, comment) VALUES (nextval('nc_oktmo_seq'), '79618430','0','- Уляпское','аул Уляп');
INSERT INTO nc_oktmo (id, code, control_number, name, comment) VALUES (nextval('nc_oktmo_seq'), '79618435','7','- Хатукайское','аул Хатукай');
INSERT INTO nc_oktmo (id, code, control_number, name, comment) VALUES (nextval('nc_oktmo_seq'), '79622000','6','Майкопский муниципальный район','п Тульский');
INSERT INTO nc_oktmo (id, code, control_number, name, comment) VALUES (nextval('nc_oktmo_seq'), '79622400','8','Сельские поселения Майкопского муниципального района/','');
INSERT INTO nc_oktmo (id, code, control_number, name, comment) VALUES (nextval('nc_oktmo_seq'), '79622402','2','- Абадзехское','ст-ца Абадзехская');
INSERT INTO nc_oktmo (id, code, control_number, name, comment) VALUES (nextval('nc_oktmo_seq'), '79622407','9','- Даховское','ст-ца Даховская');
INSERT INTO nc_oktmo (id, code, control_number, name, comment) VALUES (nextval('nc_oktmo_seq'), '79622420','0','- Кировское','х Северо-Восточные Сады');
INSERT INTO nc_oktmo (id, code, control_number, name, comment) VALUES (nextval('nc_oktmo_seq'), '79622425','7','- Краснооктябрьское','п Краснооктябрьский');
INSERT INTO nc_oktmo (id, code, control_number, name, comment) VALUES (nextval('nc_oktmo_seq'), '79622428','9','- Красноульское','х Красная Улька');
INSERT INTO nc_oktmo (id, code, control_number, name, comment) VALUES (nextval('nc_oktmo_seq'), '79622434','6','- Кужорское','ст-ца Кужорская');
INSERT INTO nc_oktmo (id, code, control_number, name, comment) VALUES (nextval('nc_oktmo_seq'), '79622447','4','- Победенское','п Совхозный');
INSERT INTO nc_oktmo (id, code, control_number, name, comment) VALUES (nextval('nc_oktmo_seq'), '79622452','4','- Тимирязевское','п Тимирязева');
INSERT INTO nc_oktmo (id, code, control_number, name, comment) VALUES (nextval('nc_oktmo_seq'), '79622455','6','- Тульское','п Тульский');
INSERT INTO nc_oktmo (id, code, control_number, name, comment) VALUES (nextval('nc_oktmo_seq'), '79622457','0','- Каменномостское','п Каменномостский');
INSERT INTO nc_oktmo (id, code, control_number, name, comment) VALUES (nextval('nc_oktmo_seq'), '79630000','0','Тахтамукайский муниципальный район','аул Тахтамукай');
INSERT INTO nc_oktmo (id, code, control_number, name, comment) VALUES (nextval('nc_oktmo_seq'), '79630100','6','Городские поселения Тахтамукайского муниципального района/','');
INSERT INTO nc_oktmo (id, code, control_number, name, comment) VALUES (nextval('nc_oktmo_seq'), '79630157','9','- Энемское','пгт Энем');
INSERT INTO nc_oktmo (id, code, control_number, name, comment) VALUES (nextval('nc_oktmo_seq'), '79630159','3','- Яблоновское','пгт Яблоновский');
INSERT INTO nc_oktmo (id, code, control_number, name, comment) VALUES (nextval('nc_oktmo_seq'), '79630400','2','Сельские поселения Тахтамукайского муниципального района/','');
INSERT INTO nc_oktmo (id, code, control_number, name, comment) VALUES (nextval('nc_oktmo_seq'), '79630405','9','- Афипсипское','аул Афипсип');
INSERT INTO nc_oktmo (id, code, control_number, name, comment) VALUES (nextval('nc_oktmo_seq'), '79630415','5','- Старобжегокайское','аул Старобжегокай');
INSERT INTO nc_oktmo (id, code, control_number, name, comment) VALUES (nextval('nc_oktmo_seq'), '79630417','7','- Козетское','аул Козет');
INSERT INTO nc_oktmo (id, code, control_number, name, comment) VALUES (nextval('nc_oktmo_seq'), '79630419','4','- Шенджийское','аул Шенджий');
INSERT INTO nc_oktmo (id, code, control_number, name, comment) VALUES (nextval('nc_oktmo_seq'), '79630420','5','- Тахтамукайское','аул Тахтамукай');
INSERT INTO nc_oktmo (id, code, control_number, name, comment) VALUES (nextval('nc_oktmo_seq'), '79633000','4','Теучежский муниципальный район','аул Понежукай');
INSERT INTO nc_oktmo (id, code, control_number, name, comment) VALUES (nextval('nc_oktmo_seq'), '79633100','2','Городские поселения Теучежского муниципального района/','');
INSERT INTO nc_oktmo (id, code, control_number, name, comment) VALUES (nextval('nc_oktmo_seq'), '79633155','8','- Тлюстенхабльское','пгт Тлюстенхабль');
INSERT INTO nc_oktmo (id, code, control_number, name, comment) VALUES (nextval('nc_oktmo_seq'), '79633400','6','Сельские поселения Теучежского муниципального района/','');
INSERT INTO nc_oktmo (id, code, control_number, name, comment) VALUES (nextval('nc_oktmo_seq'), '79633405','2','- Ассоколайское','аул Ассоколай');
INSERT INTO nc_oktmo (id, code, control_number, name, comment) VALUES (nextval('nc_oktmo_seq'), '79633410','2','- Вочепшийское','аул Вочепший');
INSERT INTO nc_oktmo (id, code, control_number, name, comment) VALUES (nextval('nc_oktmo_seq'), '79633415','9','- Джиджихабльское','аул Джиджихабль');
INSERT INTO nc_oktmo (id, code, control_number, name, comment) VALUES (nextval('nc_oktmo_seq'), '79633430','5','- Понежукайское','аул Понежукай');
INSERT INTO nc_oktmo (id, code, control_number, name, comment) VALUES (nextval('nc_oktmo_seq'), '79633433','7','- Пчегатлукайское','аул Пчегатлукай');
INSERT INTO nc_oktmo (id, code, control_number, name, comment) VALUES (nextval('nc_oktmo_seq'), '79633445','8','- Габукайское','аул Габукай');
INSERT INTO nc_oktmo (id, code, control_number, name, comment) VALUES (nextval('nc_oktmo_seq'), '79640000','4','Шовгеновский муниципальный район','аул Хакуринохабль');
INSERT INTO nc_oktmo (id, code, control_number, name, comment) VALUES (nextval('nc_oktmo_seq'), '79640400','6','Сельские поселения Шовгеновского муниципального района/','');
INSERT INTO nc_oktmo (id, code, control_number, name, comment) VALUES (nextval('nc_oktmo_seq'), '79640405','2','- Джерокайское','аул Джерокай');
INSERT INTO nc_oktmo (id, code, control_number, name, comment) VALUES (nextval('nc_oktmo_seq'), '79640408','4','- Дукмасовское','х Дукмасов');
INSERT INTO nc_oktmo (id, code, control_number, name, comment) VALUES (nextval('nc_oktmo_seq'), '79640412','7','- Заревское','п Зарево');
INSERT INTO nc_oktmo (id, code, control_number, name, comment) VALUES (nextval('nc_oktmo_seq'), '79640425','5','- Хатажукайское','аул Пшичо');
INSERT INTO nc_oktmo (id, code, control_number, name, comment) VALUES (nextval('nc_oktmo_seq'), '79640430','5','- Хакуринохабльское','аул Хакуринохабль');
INSERT INTO nc_oktmo (id, code, control_number, name, comment) VALUES (nextval('nc_oktmo_seq'), '79640435','1','- Мамхегское','аул Мамхег');
INSERT INTO nc_oktmo (id, code, control_number, name, comment) VALUES (nextval('nc_oktmo_seq'), '79700000','2','Городские округа Республики Адыгеи (Адыгеи)/','');
INSERT INTO nc_oktmo (id, code, control_number, name, comment) VALUES (nextval('nc_oktmo_seq'), '79701000','7','- город Майкоп','г Майкоп');
INSERT INTO nc_oktmo (id, code, control_number, name, comment) VALUES (nextval('nc_oktmo_seq'), '79703000','6','- город Адыгейск','г Адыгейск');
